// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZMP-1ysf9gJZWMks8YYrTxPcglKgRakE',
    appId: '1:325387804027:web:bbca784074f72a45aef1de',
    messagingSenderId: '325387804027',
    projectId: 'skillswap-89289',
    authDomain: 'skillswap-89289.firebaseapp.com',
    storageBucket: 'skillswap-89289.firebasestorage.app',
    measurementId: 'G-XD9EDH11K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-PbhR1Mij0pVcmlWVbMgVrCDKqhY1JEI',
    appId: '1:325387804027:android:e7e7dcfc77c0d1bbaef1de',
    messagingSenderId: '325387804027',
    projectId: 'skillswap-89289',
    storageBucket: 'skillswap-89289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA13p6c-Mte6dVSg0l0vK0-ze9U3Z5sHsM',
    appId: '1:325387804027:ios:74fe1ba90254728faef1de',
    messagingSenderId: '325387804027',
    projectId: 'skillswap-89289',
    storageBucket: 'skillswap-89289.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA13p6c-Mte6dVSg0l0vK0-ze9U3Z5sHsM',
    appId: '1:325387804027:ios:74fe1ba90254728faef1de',
    messagingSenderId: '325387804027',
    projectId: 'skillswap-89289',
    storageBucket: 'skillswap-89289.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZMP-1ysf9gJZWMks8YYrTxPcglKgRakE',
    appId: '1:325387804027:web:d1704bd67439fbb7aef1de',
    messagingSenderId: '325387804027',
    projectId: 'skillswap-89289',
    authDomain: 'skillswap-89289.firebaseapp.com',
    storageBucket: 'skillswap-89289.firebasestorage.app',
    measurementId: 'G-L457MSKKH4',
  );
}
